### PR TITLE
ADDED: terraform state and variables added

### PR DESCRIPTION
**Pull request by Nanadennis**
Mr. Daniel /Mr.William
Please have a quick Look at my assignment .I do have some few questions

### CODE REVIEW

**Comment by 582Bamfo** [comment]
Hi Nana, I can't see your variable file.

**Comment by Nanadennis** [comment]
okay I pushed it what should I do

**Comment by 582Bamfo** [comment]
Thank you! I can see the changes now.

Good job!
It can be merge now

**Comment by Nanadennis** [comment]
great ,thank you

**Comment by Nanadennis** [comment]
Please 1.
should we send pictures of our s3 bucket?
should I go ahead and destroy?

Thank you

**Pull request merged**
